language: node_js
node_js:
  - 8
  - 10
  - 12
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: "npm test"
after_script: "./node_modules/.bin/coveralls < coverage/lcov.info"
